#!/bin/bash
clear
echo 'Daftar Query Dorking Yang Saya Kumpulkan'
echo ' '
echo 'tekan 1 lalu enter untuk lihat'
echo 'tekan 0 lalu enter untuk info'
read list

if [ $list -ge 1 ]
then
    echo 'site:'
    echo 'memberikan hasil pada situs tertentu'
    echo '========================================'
    echo 'inurl:'
    echo 'hasil yang keluar hanya website yang'
    echo 'memiliki domain dengan kata tersebut'
    echo '========================================'
    echo 'intext:'
    echo 'memberikan hasil berdasarkan isi'
    echo 'text website'
    echo '========================================'
    echo '-:'
    echo 'mencari hasil yang tidak memiliki'
    echo 'kata tersebut'
    echo '========================================'
    echo '@:'
    echo 'mencari media sosial'
    echo '========================================'
    echo 'OR:'
    echo 'menggabungkan hasil pencarian'
    echo '========================================'
    echo 'AND:'
    echo 'mencari hasil pencarian yang memiliki'
    echo 'kata pertama dan kata kedua'
    echo '========================================'
    echo '" ":'
    echo 'mencari kata/kalimat secara keseluruhan'
    echo '========================================'
    echo '|:'
    echo 'mencari 2 hasil pencarian, dimana'
    echo 'pencarian tersebut menemukan salah satu'
    echo 'dari dua keyword yang kita cari'
    echo '========================================'
    echo 'filetype:'
    echo 'mencari suatu file dengan format'
    echo 'yang kita inginkan'
    echo '========================================'
    echo 'intitle:'
    echo 'mencari hasil pencarian yang judulnya'
    echo 'adalah kata atau kalimat '
    echo '========================================'
    echo '*:'
    echo 'mencari halaman yang berisi “apa saja”'
    echo 'sebelum kata Anda'
    echo '========================================'
    echo 'cache:'
    echo 'menunjukkan versi cache dari'
    echo 'situs web mana pun'
    echo '========================================'
    echo '+:'
    echo 'mendeteksi halaman yang menggunakan'
    echo 'lebih dari satu kunci tertentu'
    echo '========================================'
    echo 'info:'
    echo 'penjelasan kata tersebut,,'
    echo 'cocok untuk pelajar'
    echo '========================================'
    echo 'inanchor:'
    echo 'search link anchor text '
    echo '========================================'
    echo 'define:'
    echo 'digunakan untuk mencari definisi dari'
    echo 'kata yang anda ketik pada kotak'
    echo 'mesin pencari'
    echo '========================================'
    echo 'faktanya nih,, query dorking bisa'
    echo 'di gabungkan satu sama lain'
else
    echo 'name: x1'
    echo 'team: ProgrammerNewbieIndonesia'
    echo '      BugHunterNewbieIndonesia'
    echo '      TermuxNewbieIndonesia'
    echo '      CTFindonesiaBelajar'
    echo '      IOTindonesiaBelajar'
    echo 'version-1.1'
    echo '+62'
    echo 'film $mr.robot'
fi


